spring.application.name=ServidorPruebaDB
spring.datasource.url=jdbc:postgresql://localhost:5432/estudiantes3
spring.datasource.username=h.franz.folgueira
spring.datasource.password=Fra9753etl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#
spring.hazelcast.config=classpath:config/my-hazelcast.xml
spring.cache.type=hazelcast
